_target_: agents.models.bc.bc_agent.BC_Agent
_recursive_: false

action_seq_size: ${inference_action_seq}
obs_seq_len: ${obs_seq}

model:
  _target_: agents.models.bc.bc_agent.BC_Policy
  _recursive_: false

  visual_input: True
  device: ${device}

  model:
    _target_: agents.models.bc.transformer.Enc_only
    _recursive_: false
    state_dim: 256 #${obs_dim}
    action_dim: ${action_dim}
    goal_conditioned: False
    goal_seq_len: 10
    obs_seq_len: ${obs_seq}
    action_seq_len: ${train_action_seq}
    embed_pdrob: 0
    # Architecture details
    embed_dim: 128 #${n_embd}
    device: ${device}
    linear_output: true

    encoder:
      _target_: agents.models.oc_ddpm.mamba.MixerModel
      ssm_cfg: ${mamba_ssm_cfg}
      d_model: 128
      n_layer: ${n_layers}
      norm_epsilon: 1e-5
      rms_norm: False
      fused_add_norm: False
      residual_in_fp32: False
      device: ${device}

  obs_encoder:
    _target_: agents.module.vision.multi_image_obs_encoder.MultiImageObsEncoder
    shape_meta: &shape_meta
      # acceptable types: rgb, low_dim
      obs:
        agentview_rgb:
          shape: [ 3, 128, 128 ]
          type: rgb
        eye_in_hand_rgb:
          shape: [ 3, 128, 128 ]
          type: rgb

    rgb_model:
      _target_: agents.module.vision.get_model.get_resnet
      input_shape: [ 3, 128, 128 ]
      output_size: 128
    resize_shape: null
    #    crop_shape: [ 84, 84 ]
    # constant center crop
    random_crop: False
    use_group_norm: True
    share_rgb_model: False
    imagenet_norm: True

trainset: ${trainset}
valset: ${valset}

optimization:
  _target_: torch.optim.Adam
  lr: 5e-4
  weight_decay: 0

train_batch_size: ${train_batch_size}
val_batch_size: ${val_batch_size}
num_workers: ${num_workers}
epoch: ${epoch}
device: ${device}
scale_data: ${scale_data}
eval_every_n_epochs: ${eval_every_n_epochs}